### ISSUE TITLE
name collision

### ISSUE THREAD

**Issue by dpep** [dobs/autographql#1]
Hey Daniel!  I was working on my own autographql library and went to publish it to rubygems.org, only to discover that you were on the same road.  And more bizarrely, we're both Daniel.

I poked around your code and it looks like a great start but that progress might have fallen off a while ago.  Are you still using it?  If not, would you please consider relinquishing the gem name so I can put it to use?

Here's what I've got so far: https://github.com/dpep/rb_autographql

https://rubygems.org/gems/autographql

Thanks,

-Daniel

**Comment by dobs** [comment]
Absolutely -- my work on this stalled out almost immediately.

I'll see about deleting the project tonight. Alternatively if you can provide an email I'll add you as an owner and leave control in your hands.

**Comment by dpep** [comment]
awesome!!  my email is pepper.daniel@gmail.com - whichever route is easiest for you

**Comment by dobs** [comment]
You've been added as an owner on the project -- feel free to remove me as an owner and otherwise treat it as your own. And good luck with your project!

I've also deleted your previous comment for email-privacy. :)

**Comment by dpep** [comment]
thanks so much!
